### ISSUE TITLE
MVPリリース レビュー依頼

### ISSUE THREAD

**Issue by ITOmaSabai** [ITOmaSabai/BackHacker#48]
## 各種情報
サービス名: BackHacker.
サービスURL: https://backhacker-frontend.vercel.app/

###  MVPリリース時
- [x] ユーザー登録機能
- [x] ユーザー情報機能
- [x] ユーザーの投稿したスポット一覧機能
- [x] ユーザーのいいねしたスポット一覧機能
- [x] ログイン機能
- [x] ログアウト機能
- [x] Google Map APIを用いた機能
  - [x] スポット新規投稿機能
  - [x] スポット削除機能
  - [x] スポット編集機能
  - [x] スポット一覧機能(地図上に表示)
  - [x] いいね機能
  - [x] いいねしたスポットの一覧機能(地図上に表示)
- [x] YouTube Data APIを用いた機能
  - [x] スポットを投稿する際、自動的に動画を取得する機能

## READMEレビュー時から変更した機能
- [x] ユーザー削除(退会)機能
=> ユーザーの使用頻度を考慮して、本リリース以降に実装します。

## サービスイメージがわかるようなスクリーンショット等
- トップページ

[![Image from Gyazo](https://i.gyazo.com/10b970872ac3fdcd3703f5b1cd5dd43e.gif)](https://gyazo.com/10b970872ac3fdcd3703f5b1cd5dd43e)

- スポット一覧機能、スポット詳細機能

[![Image from Gyazo](https://i.gyazo.com/c3500744a3d2de1286dc6d0fb2087ac5.gif)](https://gyazo.com/c3500744a3d2de1286dc6d0fb2087ac5)

- プロフィール機能

[![Image from Gyazo](https://i.gyazo.com/e40c8f9f0090aedb53edcf1947eebcad.gif)](https://gyazo.com/e40c8f9f0090aedb53edcf1947eebcad)

**Comment by tmtkzk0823** [comment]
確認させていただきました！
READMEに記載されている機能をしっかり実装できていると思います！
LGTMです！
